### ISSUE TITLE
LongLiveCHIEF isn't a github user

### ISSUE THREAD

**Issue by LongLiveCHIEF** [cujarrett/glimpse#139]
this looks really cool, but unfortunately it thinks I'm not a github user.

I wonder if it has something to do with my organization affiliations and SSO enablement for one of them?  In any case, you now have a username for which to test against for strange happenings.

**Comment by LongLiveCHIEF** [comment]
icognito mode worked for me

**Comment by Torpus** [comment]
It’s always @LongLiveCHIEF…. Even when it’s not it probably is. =)
