### ISSUE TITLE
Permanent Link

### ISSUE THREAD

**Issue by rvhuang** [cujarrett/glimpse#15]
It's better to have permanent link after user input his/her GitHub account so user can directly visit the chart.

**Comment by matt-jarrett** [comment]
I think adding a link via the existing message makes sense. Their GitHub page won't have contribution data older than an year though, that's where this app helps IMO.

**Comment by cujarrett** [comment]
@rvhuang - I implemented this in #81

**Comment by cujarrett** [comment]
I also implemented the URL permanent link prior.

Example: https://www.glimpse.ninja/rvhuang
