### ISSUE TITLE
App message doesn't clear on text change

### ISSUE THREAD

**Issue by cujarrett** [cujarrett/glimpse#71]
## What
If you search for any user and then backspace the text box it clears the content pane but doesn't reset the message text.

<img width="1419" alt="Screen Shot 2020-01-08 at 12 01 25 AM" src="https://user-images.githubusercontent.com/16245634/71954209-1bdea980-31aa-11ea-9247-5af1805ad4ac.png">

🐛

**Comment by vicky724** [comment]
I want to take it up.

**Comment by cujarrett** [comment]
Awesome @vicky724 👍 

The app is sadly down as I migrate it from Heroku to AWS. You should be able to do the development locally without issue though. Sorry for the inconvenience. I appreciate youre interest in the project.

**Comment by cujarrett** [comment]
@vicky724 , I got most of the DNS completed on AWS tonight. Happy hacking.

https://www.glimpse.ninja

**Comment by cujarrett** [comment]
Fixed by @vicky724 🎉 in #76
